/* eslint-disable */
/* demo/demo-data.js — brand configs for the live sample landing pages.
   Demonstrates the operator's "reskin per prospect" — one build, swap the config. */
window.DEMO_BRANDS = {
  plumbing: {
    key: "plumbing",
    name: "Rose City Plumbing",
    mark: "RC",
    city: "Portland",
    phone: "(503) 555-0142",
    phoneHref: "tel:+15035550142",
    pairing: "a",
    brand: "#0E8C86",
    eyebrow: "Licensed plumbers · Portland metro",
    h1: "Portland plumbers who show up when we say we will.",
    lede: "Drains, water heaters, leaks, repipes. Upfront pricing, same-day slots, and a two-year warranty on every install.",
    trust: { years: "17", rating: "4.9", reviews: "312", license: "PL-1234" },
    schedTitle: "Book a visit. We'll text to confirm within 15 minutes.",
    services: [
      { icon: "droplets", name: "Drain cleaning", desc: "Slow or clogged drains cleared fast — kitchen, bath, or main line." },
      { icon: "flame", name: "Water heaters", desc: "Tank and tankless repair and install. We carry common models on the truck." },
      { icon: "search", name: "Leak detection", desc: "Cameras and acoustic gear find it before we open a wall." },
      { icon: "wrench", name: "Repiping", desc: "Copper, PEX, and PVC. Clean work, tidy finish, no surprises." },
      { icon: "shower-head", name: "Fixture install", desc: "Faucets, toilets, disposals, and shower valves done right." },
      { icon: "gauge", name: "Sewer & camera", desc: "Sewer line inspection and repair with a full camera report." },
    ],
    reviews: [
      { quote: "Burst pipe under the kitchen sink on a Sunday. They texted back in ten minutes and had it fixed by noon. Told me the price before they started.", name: "Dana M.", area: "Sellwood" },
      { quote: "New tankless heater installed in an afternoon. Clean work, walked me through the warranty, no upsell. This is how it should be.", name: "Marcus T.", area: "Beaumont" },
    ],
  },
  hvac: {
    key: "hvac",
    name: "Cascade Heating & Air",
    mark: "CH",
    city: "Portland",
    phone: "(503) 555-0188",
    phoneHref: "tel:+15035550188",
    pairing: "a",
    brand: "#B23A2E",
    eyebrow: "Heating & cooling · Portland metro",
    h1: "Warm in winter, cool in summer, fixed the same day.",
    lede: "Furnace and AC repair, new system installs, and tune-ups. Flat-rate pricing and a comfort guarantee on every job.",
    trust: { years: "21", rating: "4.9", reviews: "418", license: "HV-7781" },
    schedTitle: "Book a visit. We'll text to confirm within 15 minutes.",
    services: [
      { icon: "snowflake", name: "AC repair", desc: "Not cooling? We diagnose fast and carry common parts on the van." },
      { icon: "flame", name: "Furnace service", desc: "Repair, tune-up, and replacement for gas and electric systems." },
      { icon: "fan", name: "New installs", desc: "Right-sized systems with upfront pricing — no guesswork." },
      { icon: "wind", name: "Ductwork", desc: "Sealing, repair, and balancing so every room stays comfortable." },
      { icon: "thermometer", name: "Thermostats", desc: "Smart thermostat install and setup, done in one visit." },
      { icon: "shield-check", name: "Maintenance plans", desc: "Two visits a year to keep things running and the warranty valid." },
    ],
    reviews: [
      { quote: "AC died in a July heat wave. They had a tech out the same afternoon and the price was exactly what they quoted on the phone.", name: "Priya S.", area: "Hillsboro" },
      { quote: "New furnace before winter. Tidy install, explained the whole system, and the house has never been more even. Highly recommend.", name: "Greg L.", area: "Beaverton" },
    ],
  },
  electrical: {
    key: "electrical",
    name: "Bridgetown Electric",
    mark: "BE",
    city: "Portland",
    phone: "(503) 555-0119",
    phoneHref: "tel:+15035550119",
    pairing: "a",
    brand: "#C2410C",
    eyebrow: "Licensed electricians · Portland metro",
    h1: "Licensed electricians who leave it safer than they found it.",
    lede: "Panel upgrades, EV chargers, rewires, and lighting. Permitted work, clean finish, and a clear price before we start.",
    trust: { years: "14", rating: "5.0", reviews: "207", license: "EL-4420" },
    schedTitle: "Book a visit. We'll text to confirm within 15 minutes.",
    services: [
      { icon: "zap", name: "Panel upgrades", desc: "200-amp service and panel swaps, permitted and inspected." },
      { icon: "plug", name: "EV chargers", desc: "Level 2 home charger install, sized to your car and panel." },
      { icon: "lightbulb", name: "Lighting", desc: "Recessed, under-cabinet, and outdoor lighting done cleanly." },
      { icon: "house", name: "Rewires", desc: "Knob-and-tube and aluminum replacement for older Portland homes." },
      { icon: "shield-check", name: "Safety checks", desc: "Full inspection with a plain-English report and photos." },
      { icon: "battery-charging", name: "Backup power", desc: "Generator and battery hookups for when the grid goes down." },
    ],
    reviews: [
      { quote: "Upgraded our panel and added an EV charger in one day. Pulled the permit, walked me through everything, spotless cleanup.", name: "Helen K.", area: "Alberta" },
      { quote: "Old house, scary wiring. They mapped it out, gave me a clear price, and made it safe without tearing up the walls.", name: "Tomás R.", area: "St. Johns" },
    ],
  },
};
